scan_filter_chain:
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: true
    lower_threshold: 0.05
    upper_threshold: 1.5
    lower_replacement_value: nan
    upper_replacement_value: nan



